### ISSUE TITLE
Meteor.user() filled right after login, empty after reloading page.

### ISSUE THREAD

**Issue by Octopixell** [AlexBeauchemin/meteor-accounts-twitch#1]
Hi there! 

Thanks for making this awesome package! I'm having a little issue trying to implement it though. 
When I click on the button and authorize my Twitch App it seems to all go just fine. When the popup closes both `Meteor.user()` and `Meteor.userId()` are filled and it seems a user is authenticated.

When I refresh the page however; `Meteor.user()` is undefined. 

I'm unsure what I'm doing wrong here.

What also doesn't seem to be working is the following router hook (iron-router):

```
Router.onBeforeAction(function () {
    // if the user is not logged in, redirect to Login template
    if (!Meteor.userId())
    {
        Router.go('login');
        this.next();
    }
    // otherwise don't hold up the rest of hooks or our route/action function
    // from running
    else
    {
        this.next();
    }
});
```

This however works for all other login methods. I'm using Meteor 1.3.4.1, maybe the package isn't compatible I don't know.

Please let me know if I need to supply more data to get this resolved :)

**Comment by AlexBeauchemin** [comment]
I'm using 1.3.2.4 on one of my project and it seems to work fine. I can test this later see if the problem could come from a more recent version.

Meanwhile you can check out how I made the login process in this project (refactor to react still in dev) and see what is different https://github.com/AlexBeauchemin/ambiant/tree/react/app-react
My best quick guess is that your problem might be in your routing. Do you have a project on github that I can look into?

**Comment by Octopixell** [comment]
Hey Alex,

Thanks for getting back so quick, I don't have anything on Git yet sorry. But I'll compare my work to yours asap and get back to you, thanks!

**Comment by Octopixell** [comment]
Hey @AlexBeauchemin I've checked it again and it does seem to be the fact that I didn't redirect away from the login page after a login. Now that I do, it seems to work just fine :smile: 

Thanks again for making this great package!
